basePath: /
definitions:
  domain.Debt:
    properties:
      amount:
        example: 50.25
        type: number
      from_id:
        example: 2
        type: integer
      to_id:
        example: 1
        type: integer
    type: object
  domain.Fund:
    properties:
      author_id:
        example: 1
        type: integer
      created_at:
        type: string
      id:
        example: 1
        type: integer
      invite_code:
        example: aB12cD
        type: string
      name:
        example: Trip to Paris
        type: string
    type: object
  domain.FundPaginationRequest:
    properties:
      fund_id:
        example: 1
        type: integer
      limit:
        example: 20
        type: integer
      offset:
        example: 0
        type: integer
    type: object
  domain.FundRequest:
    properties:
      id:
        example: 1
        type: integer
      invite_code:
        example: aB12cD
        type: string
    type: object
  domain.JoinFundRequest:
    properties:
      invite_code:
        example: aB12cD
        type: string
    type: object
  domain.Pagination:
    properties:
      limit:
        example: 20
        type: integer
      offset:
        example: 0
        type: integer
    type: object
  domain.PingResponse:
    properties:
      pong:
        type: boolean
    type: object
  domain.Purchase:
    properties:
      amount:
        example: 150.5
        type: number
      created_at:
        type: string
      description:
        example: Taxi to hotel
        type: string
      fund_id:
        example: 1
        type: integer
      id:
        example: 1
        type: integer
      payer:
        $ref: '#/definitions/domain.User'
    type: object
  domain.RemoveUserRequest:
    properties:
      fund_id:
        example: 1
        type: integer
      user_id:
        example: 2
        type: integer
    type: object
  domain.SessionCheckRequest:
    properties:
      uuid:
        example: 550e8400-e29b-41d4-a716-446655440000
        type: string
    type: object
  domain.SettleFund:
    properties:
      cost:
        example: 150.5
        type: number
      description:
        example: Taxi to hotel
        type: string
      fund_id:
        example: 1
        type: integer
    type: object
  domain.Settlement:
    properties:
      average:
        example: 150.5
        type: number
      debts:
        items:
          $ref: '#/definitions/domain.Debt'
        type: array
      total_amount:
        example: 451.5
        type: number
    type: object
  domain.User:
    properties:
      created_at:
        type: string
      first_name:
        example: Alex
        type: string
      id:
        example: 1
        type: integer
      is_virtual:
        example: false
        type: boolean
      tg_id:
        example: 123456789
        type: integer
      username:
        example: ganfay
        type: string
    type: object
  domain.VirtualUserRequest:
    properties:
      first_name:
        example: Alex
        type: string
      fund_id:
        example: 1
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: API documentation for my application.
  title: My API
  version: "1.0"
paths:
  /api/v1/auth/telegram/access:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: generate and get access token if refresh valid
      tags:
      - sessions
  /api/v1/auth/telegram/init:
    post:
      consumes:
      - application/json
      description: Returns UUID.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
      summary: Create session
      tags:
      - sessions
  /api/v1/auth/telegram/status:
    get:
      consumes:
      - application/json
      description: Returns the current status of a session by UUID.
      parameters:
      - description: Session UUID
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.SessionCheckRequest'
      produces:
      - application/json
      responses:
        "200":
          description: pending
          schema:
            type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Check session status
      tags:
      - sessions
  /api/v1/auth/telegram/tokens:
    post:
      consumes:
      - application/json
      parameters:
      - description: Session UUID
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.SessionCheckRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: generate refresh, access jwt tokens
      tags:
      - sessions
  /api/v1/fund:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Only fund id must be here
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.Fund'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: delete fund
      tags:
      - fund
    get:
      consumes:
      - application/json
      parameters:
      - description: Pagination
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.Pagination'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Fund'
            type: array
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: get funds by current user iid
      tags:
      - fund
    post:
      consumes:
      - application/json
      parameters:
      - description: Only fund name must be here
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.Fund'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Fund'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: create fund
      tags:
      - fund
  /api/v1/fund/balance:
    get:
      consumes:
      - application/json
      parameters:
      - description: Fund id
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.FundRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Settlement'
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: get fund settlement
      tags:
      - fund
  /api/v1/fund/expense:
    post:
      consumes:
      - application/json
      parameters:
      - description: Expense data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.SettleFund'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: add expense to fund
      tags:
      - fund
  /api/v1/fund/info:
    get:
      consumes:
      - application/json
      parameters:
      - description: Fund id or invite code
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.FundRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Fund'
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: get fund info
      tags:
      - fund
  /api/v1/fund/join:
    post:
      consumes:
      - application/json
      parameters:
      - description: Invite code
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.JoinFundRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Fund'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: join fund by invite code
      tags:
      - fund
  /api/v1/fund/member:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Fund id and user id
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.RemoveUserRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: remove user from fund
      tags:
      - fund
  /api/v1/fund/members:
    get:
      consumes:
      - application/json
      parameters:
      - description: Fund id
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.FundRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.User'
            type: array
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: get fund members
      tags:
      - fund
  /api/v1/fund/purchases:
    get:
      consumes:
      - application/json
      parameters:
      - description: Fund id and pagination
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.FundPaginationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Purchase'
            type: array
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: get fund purchase history
      tags:
      - fund
  /api/v1/fund/virtual-users:
    get:
      consumes:
      - application/json
      parameters:
      - description: Fund id and pagination
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.FundPaginationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.User'
            type: array
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: get virtual fund members
      tags:
      - fund
    post:
      consumes:
      - application/json
      parameters:
      - description: Virtual user data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.VirtualUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.User'
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
      summary: create and add virtual user to fund
      tags:
      - fund
  /api/v1/ping:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.PingResponse'
        "500":
          description: Internal Server Error
      summary: ping
      tags:
      - fund
swagger: "2.0"
